apiVersion: v1
kind: Service
metadata:
  name: {{ include "access-issuer.fullname" . }}
  labels:
    {{- include "access-issuer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "access-issuer.selectorLabels" . | nindent 4 }}
  ports:
    - name: issuer
      port: {{ .Values.listeners.port }}
      targetPort: issuer
