{{- if eq .Values.renders "app" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "access-roster.fullname" . }}
  labels:
    {{- include "access-roster.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "access-roster.selectorLabels" . | nindent 4 }}
  ports:
    - name: issuer
      port: {{ include "access-roster.port" . }}
      targetPort: issuer
{{ end -}}
